export type BrokerId = "fxglory" | "hankotrade" | "midasfx" | "n1cm" | "hfm" | "lmfx" | "coinexx" | "plexytrade" | "exness" | "pepperstone" | "xm" | "fxtm" | "fbs" | "etoro" | "fxpro" | "oanda" | "ig" | "forexcom" | "interactivebrokers" | "avatrade" | "charlesschwab" | "tastyfx";

export type BrokerType = "offshore" | "regulated";

export type BrokerRegion = "US" | "INTL" | "BOTH";

export type Broker = {
  id: BrokerId;
  name: string;
  type: BrokerType;
  region: BrokerRegion;

  // Temel bilgiler
  rating: number;
  minDeposit: number; // numeric for sorting
  minDepositDisplay: string;
  leverage: string;
  leverageValue: number; // numeric for sorting (1:500 = 500)
  spreads: string;
  spreadsFrom: number; // numeric for sorting

  // Düzenleme
  regulation: string;
  headquarters: string;
  foundedYear: number;

  // Özellikler
  usAccepted: boolean;
  platforms: string[];
  accountTypes: string[];
  paymentMethods: string[];
  cryptoDeposits: boolean;
  negativeBalanceProtection: boolean;

  // Kategorik puanlar (1-10)
  scores: {
    tradingConditions: number;
    platformTools: number;
    customerSupport: number;
    depositWithdrawal: number;
    trustReputation: number;
  };

  // Artılar/Eksiler
  pros: string[];
  cons: string[];

  // URLs
  reviewUrl: string;
  siteUrl: string;
  affiliateUrl?: string;
  logoSrc: string;
  featured?: boolean;
};

const env = import.meta.env as unknown as Record<string, string | undefined>;

export const brokers: Record<BrokerId, Broker> = {
  midasfx: {
    id: "midasfx",
    name: "MidasFX",
    type: "offshore",
    region: "BOTH",
    rating: 4.8,
    minDeposit: 50,
    minDepositDisplay: "$50",
    leverage: "1:500",
    leverageValue: 500,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "FSA",
    headquarters: "St. Vincent",
    foundedYear: 2019,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["Standard", "ECN", "VIP"],
    paymentMethods: ["Crypto", "Wire Transfer"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.2,
      platformTools: 9.0,
      customerSupport: 9.0,
      depositWithdrawal: 9.5,
      trustReputation: 9.0,
    },
    pros: [
      "FSA regulated broker",
      "0.0 pip raw spreads",
      "Fast crypto withdrawals",
      "US clients accepted",
      "MT4 & MT5 platforms",
    ],
    cons: [
      "Higher minimum deposit ($50)",
      "Limited educational resources",
    ],
    reviewUrl: "/review/midasfx",
    siteUrl: "https://www.midasfx.com/?ib=1136695",
    affiliateUrl: "https://my.midasfx.com/?ib=1136695",
    logoSrc: "/brokers/midasfx.png",
    featured: true,
  },
  hankotrade: {
    id: "hankotrade",
    name: "Hankotrade",
    type: "offshore",
    region: "BOTH",
    rating: 4.7,
    featured: true,
    minDeposit: 10,
    minDepositDisplay: "$10",
    leverage: "1:500",
    leverageValue: 500,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "Seychelles FSA",
    headquarters: "Seychelles",
    foundedYear: 2020,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["STP", "ECN", "ECN Plus"],
    paymentMethods: ["Crypto"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.5,
      platformTools: 9.0,
      customerSupport: 8.5,
      depositWithdrawal: 9.0,
      trustReputation: 8.5,
    },
    pros: [
      "Zero spread accounts",
      "Low $10 minimum deposit",
      "Fast crypto deposits",
      "US clients accepted",
      "No commission on STP",
    ],
    cons: [
      "Crypto-only deposits",
      "Limited regulation",
      "Newer broker (2020)",
    ],
    reviewUrl: "/review/hankotrade",
    siteUrl: "https://hankotrade.com",
    affiliateUrl: "https://login.hankotrade.com/register?refLink=OTE0Mzk=&refRm=11",
    logoSrc: "/brokers/hankotrade.png",
  },
  fxglory: {
    id: "fxglory",
    name: "FXGlory",
    type: "offshore",
    region: "BOTH",
    rating: 4.2,
    minDeposit: 1,
    minDepositDisplay: "$1",
    leverage: "1:3000",
    leverageValue: 3000,
    spreads: "0.1 pips",
    spreadsFrom: 0.1,
    regulation: "SVG FSA",
    headquarters: "St. Vincent",
    foundedYear: 2011,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["Standard", "Premium", "VIP", "Scalping"],
    paymentMethods: ["Crypto", "Wire Transfer", "Credit Card"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.5,
      platformTools: 9.0,
      customerSupport: 9.5,
      depositWithdrawal: 9.5,
      trustReputation: 9.0,
    },
    pros: [
      "Lowest minimum deposit ($1)",
      "Highest leverage (1:3000)",
      "Multiple deposit methods",
      "US clients accepted",
      "24/7 customer support",
    ],
    cons: [
      "Not regulated by major authorities",
      "Higher spreads than ECN brokers",
    ],
    reviewUrl: "/review/fxglory",
    siteUrl: env.VITE_FXGLORY_VISIT_URL || "https://fxglory.com/?ib=82027",
    affiliateUrl: env.VITE_FXGLORY_AFFILIATE_URL || "https://app.fxglory.com/auth/register?ib=82027",
    logoSrc: "/brokers/fxglory.webp",
  },
  n1cm: {
    id: "n1cm",
    name: "N1CM",
    type: "offshore",
    region: "BOTH",
    rating: 4.3,
    minDeposit: 1,
    minDepositDisplay: "$1",
    leverage: "1:1000",
    leverageValue: 1000,
    spreads: "0.5 pips",
    spreadsFrom: 0.5,
    regulation: "FSA",
    headquarters: "St. Vincent",
    foundedYear: 2017,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["Standard", "Pro", "VIP"],
    paymentMethods: ["Crypto", "Wire Transfer"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.0,
      platformTools: 8.5,
      customerSupport: 8.0,
      depositWithdrawal: 8.5,
      trustReputation: 8.0,
    },
    pros: [
      "Low minimum deposit ($1)",
      "High leverage (1:1000)",
      "Crypto deposits accepted",
      "US clients accepted",
    ],
    cons: [
      "Higher spreads",
      "Limited brand recognition",
    ],
    reviewUrl: "/review/n1cm",
    siteUrl: "https://www.n1cm.com",
    affiliateUrl: env.VITE_N1CM_AFFILIATE_URL || "https://register.n1cmpro.com/en?partner_id=250473",
    logoSrc: "/brokers/n1cm.webp",
  },
  hfm: {
    id: "hfm",
    name: "HFM (HotForex)",
    type: "offshore",
    region: "INTL",
    rating: 4.6,
    featured: true,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:2000",
    leverageValue: 2000,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "CySEC, FCA, DFSA, FSCA, FSA",
    headquarters: "Cyprus",
    foundedYear: 2010,
    usAccepted: false, // Will update after confirmation
    platforms: ["MT4", "MT5", "HFM App"],
    accountTypes: ["Micro", "Premium", "Zero Spread", "PAMM", "HFcopy"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller", "Crypto"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.5,
      platformTools: 8.5,
      customerSupport: 8.0,
      depositWithdrawal: 8.5,
      trustReputation: 8.5,
    },
    pros: [
      "Multi-regulated broker (CySEC, FCA)",
      "Zero spread accounts available",
      "High leverage up to 1:2000",
      "Low minimum deposit ($0)",
      "Copy trading (HFcopy)",
      "Award-winning broker since 2010",
    ],
    cons: [
      "US clients currently NOT accepted",
      "Offshore entity for high leverage",
      "Inactivity fees apply",
    ],
    reviewUrl: "/review/hfm",
    siteUrl: "https://www.hfm.com/sv/en/?refid=30503439",
    affiliateUrl: "https://www.hfm.com/sv/en/?refid=30503439",
    logoSrc: "/brokers/hfm.svg",
  },
  tastyfx: {
    id: "tastyfx",
    name: "tastyfx",
    type: "regulated",
    region: "US",
    rating: 4.2,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "0.2 pips",
    spreadsFrom: 0.2,
    regulation: "CFTC/NFA",
    headquarters: "USA",
    foundedYear: 2023,
    usAccepted: true,
    platforms: ["tastyfx Platform", "MT4"],
    accountTypes: ["Standard"],
    paymentMethods: ["Wire Transfer", "ACH"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.5,
      platformTools: 9.0,
      customerSupport: 8.5,
      depositWithdrawal: 8.0,
      trustReputation: 9.5,
    },
    pros: [
      "CFTC/NFA regulated",
      "No minimum deposit",
      "Tight spreads",
      "Great trading platform",
      "Part of tastytrade family",
    ],
    cons: [
      "Limited leverage (1:50)",
      "Newer forex brand",
      "No crypto deposits",
    ],
    reviewUrl: "/review/tastyfx",
    siteUrl: "https://tastyfx.com",
    logoSrc: "/brokers/tastyfx.png",
  },
  charlesschwab: {
    id: "charlesschwab",
    name: "Charles Schwab",
    type: "regulated",
    region: "US",
    rating: 4.1,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "Variable",
    spreadsFrom: 0.5,
    regulation: "CFTC/NFA, SEC",
    headquarters: "USA",
    foundedYear: 1971,
    usAccepted: true,
    platforms: ["thinkorswim", "Schwab.com"],
    accountTypes: ["Standard", "Active Trader"],
    paymentMethods: ["Wire Transfer", "ACH", "Check"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.5,
      platformTools: 9.5,
      customerSupport: 9.0,
      depositWithdrawal: 9.0,
      trustReputation: 10.0,
    },
    pros: [
      "Highly trusted brand",
      "No minimum deposit",
      "Excellent thinkorswim platform",
      "Full SEC & CFTC regulation",
      "50+ years in business",
    ],
    cons: [
      "Limited leverage (1:50)",
      "Higher spreads than offshore",
      "Complex account setup",
    ],
    reviewUrl: "/review/charles-schwab",
    siteUrl: "https://www.schwab.com",
    logoSrc: "/brokers/charlesschwab.webp",
  },
  etoro: {
    id: "etoro",
    name: "eToro",
    type: "regulated",
    region: "BOTH",
    rating: 4.0,
    minDeposit: 50,
    minDepositDisplay: "$50",
    leverage: "1:30",
    leverageValue: 30,
    spreads: "1.0 pips",
    spreadsFrom: 1.0,
    regulation: "FCA, CySEC, ASIC",
    headquarters: "Israel/UK",
    foundedYear: 2007,
    usAccepted: true,
    platforms: ["eToro Platform"],
    accountTypes: ["Retail", "Professional"],
    paymentMethods: ["Credit Card", "PayPal", "Wire Transfer"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.0,
      platformTools: 9.0,
      customerSupport: 8.0,
      depositWithdrawal: 9.0,
      trustReputation: 9.0,
    },
    pros: [
      "Social/copy trading",
      "Multi-regulated broker",
      "Easy-to-use platform",
      "Crypto trading available",
    ],
    cons: [
      "Limited leverage for US",
      "Higher spreads",
      "Withdrawal fees",
    ],
    reviewUrl: "/review/etoro",
    siteUrl: "https://www.etoro.com",
    logoSrc: "/brokers/etoro.svg",
  },
  fxpro: {
    id: "fxpro",
    name: "FxPro",
    type: "regulated",
    region: "INTL",
    rating: 3.8,
    minDeposit: 100,
    minDepositDisplay: "$100",
    leverage: "1:200",
    leverageValue: 200,
    spreads: "0.6 pips",
    spreadsFrom: 0.6,
    regulation: "FCA, CySEC, FSCA",
    headquarters: "UK/Cyprus",
    foundedYear: 2006,
    usAccepted: false,
    platforms: ["MT4", "MT5", "cTrader"],
    accountTypes: ["Standard", "Raw", "Elite"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.5,
      platformTools: 9.0,
      customerSupport: 8.5,
      depositWithdrawal: 8.5,
      trustReputation: 9.0,
    },
    pros: [
      "Multiple platform options",
      "Well-regulated broker",
      "Competitive spreads",
      "Good educational resources",
    ],
    cons: [
      "US clients NOT accepted",
      "Higher minimum deposit",
    ],
    reviewUrl: "/review/fxpro",
    siteUrl: "https://www.fxpro.com",
    logoSrc: "/brokers/fxpro.png",
  },
  oanda: {
    id: "oanda",
    name: "OANDA",
    type: "regulated",
    region: "US",
    rating: 3.7,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "1.0 pips",
    spreadsFrom: 1.0,
    regulation: "CFTC/NFA",
    headquarters: "USA",
    foundedYear: 1996,
    usAccepted: true,
    platforms: ["OANDA Trade", "MT4"],
    accountTypes: ["Standard", "Premium"],
    paymentMethods: ["Wire Transfer", "ACH", "Credit Card"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.5,
      platformTools: 8.5,
      customerSupport: 8.0,
      depositWithdrawal: 8.5,
      trustReputation: 9.5,
    },
    pros: [
      "CFTC/NFA regulated",
      "No minimum deposit",
      "Long track record (1996)",
      "Advanced charting tools",
    ],
    cons: [
      "Limited leverage (1:50)",
      "Higher spreads",
      "Dated platform design",
    ],
    reviewUrl: "/review/oanda",
    siteUrl: "https://www.oanda.com",
    logoSrc: "/brokers/oanda.svg",
  },
  ig: {
    id: "ig",
    name: "IG Markets",
    type: "regulated",
    region: "US",
    rating: 3.6,
    minDeposit: 250,
    minDepositDisplay: "$250",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "0.6 pips",
    spreadsFrom: 0.6,
    regulation: "CFTC/NFA, FCA",
    headquarters: "UK",
    foundedYear: 1974,
    usAccepted: true,
    platforms: ["IG Platform", "MT4", "ProRealTime"],
    accountTypes: ["Standard", "Premium"],
    paymentMethods: ["Wire Transfer", "ACH", "Credit Card"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.0,
      platformTools: 9.0,
      customerSupport: 8.0,
      depositWithdrawal: 7.5,
      trustReputation: 10.0,
    },
    pros: [
      "50+ years in business",
      "CFTC/NFA regulated",
      "Excellent research tools",
      "Competitive spreads",
    ],
    cons: [
      "Higher minimum deposit ($250)",
      "Limited leverage (1:50)",
    ],
    reviewUrl: "/review/ig-markets",
    siteUrl: "https://www.ig.com",
    logoSrc: "/brokers/ig.svg",
  },
  forexcom: {
    id: "forexcom",
    name: "Forex.com",
    type: "regulated",
    region: "US",
    rating: 3.5,
    minDeposit: 100,
    minDepositDisplay: "$100",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "0.8 pips",
    spreadsFrom: 0.8,
    regulation: "CFTC/NFA",
    headquarters: "USA",
    foundedYear: 2001,
    usAccepted: true,
    platforms: ["Forex.com Platform", "MT4", "MT5"],
    accountTypes: ["Standard", "Commission", "DMA"],
    paymentMethods: ["Wire Transfer", "ACH", "Credit Card"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.5,
      platformTools: 8.0,
      customerSupport: 7.5,
      depositWithdrawal: 8.0,
      trustReputation: 9.5,
    },
    pros: [
      "CFTC/NFA regulated",
      "Multiple account types",
      "Good educational content",
      "Strong research tools",
    ],
    cons: [
      "Limited leverage (1:50)",
      "Average spreads",
      "Dated mobile app",
    ],
    reviewUrl: "/review/forexcom",
    siteUrl: "https://www.forex.com",
    logoSrc: "/brokers/forexcom.svg",
  },
  interactivebrokers: {
    id: "interactivebrokers",
    name: "Interactive Brokers",
    type: "regulated",
    region: "US",
    rating: 3.4,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:50",
    leverageValue: 50,
    spreads: "0.5 pips",
    spreadsFrom: 0.5,
    regulation: "CFTC/NFA, SEC",
    headquarters: "USA",
    foundedYear: 1978,
    usAccepted: true,
    platforms: ["TWS", "IBKR Mobile"],
    accountTypes: ["IBKR Pro", "IBKR Lite"],
    paymentMethods: ["Wire Transfer", "ACH"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.0,
      platformTools: 9.5,
      customerSupport: 7.0,
      depositWithdrawal: 7.5,
      trustReputation: 10.0,
    },
    pros: [
      "Lowest commissions",
      "Multi-asset trading",
      "Full SEC & CFTC regulation",
      "Advanced TWS platform",
    ],
    cons: [
      "Complex platform for beginners",
      "Limited leverage (1:50)",
      "Steep learning curve",
    ],
    reviewUrl: "/review/interactive-brokers",
    siteUrl: "https://www.interactivebrokers.com",
    logoSrc: "/brokers/interactive-brokers.svg",
  },
  lmfx: {
    id: "lmfx",
    name: "LMFX",
    type: "offshore",
    region: "BOTH",
    rating: 4.5,
    featured: true,
    minDeposit: 50,
    minDepositDisplay: "$50",
    leverage: "1:1000",
    leverageValue: 1000,
    spreads: "1.0 pips",
    spreadsFrom: 1.0,
    regulation: "Unregulated (St. Vincent)",
    headquarters: "St. Vincent",
    foundedYear: 2015,
    usAccepted: true,
    platforms: ["MT4"],
    accountTypes: ["Premium", "Fixed", "Zero"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Crypto", "Skrill", "Neteller"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.5,
      platformTools: 7.0,
      customerSupport: 7.5,
      depositWithdrawal: 7.5,
      trustReputation: 6.5,
    },
    pros: [
      "Accepts US clients",
      "High leverage (1:1000)",
      "Multiple deposit options including crypto",
      "Established since 2015",
      "$25K trading contest",
    ],
    cons: [
      "Unregulated broker",
      "MT4 only (no MT5)",
      "Higher spreads than ECN brokers",
    ],
    reviewUrl: "/review/lmfx",
    siteUrl: "https://www.lmfx.com",
    affiliateUrl: "https://lmfx.com/en/?refid=136384",
    logoSrc: "/brokers/lmfx.svg",
  },
  coinexx: {
    id: "coinexx",
    name: "Coinexx",
    type: "offshore",
    region: "BOTH",
    rating: 4.4,
    featured: true,
    minDeposit: 10,
    minDepositDisplay: "$10",
    leverage: "1:500",
    leverageValue: 500,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "Unregulated (St. Vincent)",
    headquarters: "St. Vincent",
    foundedYear: 2017,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["ECN"],
    paymentMethods: ["Bitcoin", "Ethereum", "USDT", "Litecoin"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.0,
      platformTools: 7.5,
      customerSupport: 7.0,
      depositWithdrawal: 8.5,
      trustReputation: 7.0,
    },
    pros: [
      "Accepts US clients",
      "Excellent Trustpilot rating (4.9/5)",
      "True ECN with 0.0 spreads",
      "Low minimum deposit ($10)",
      "Fast crypto withdrawals",
      "Anonymous trading possible",
    ],
    cons: [
      "Crypto-only deposits/withdrawals",
      "Unregulated broker",
      "No traditional payment methods",
    ],
    reviewUrl: "/review/coinexx",
    siteUrl: "https://www.coinexx.com",
    affiliateUrl: "https://my.coinexx.com/register?refLink=NTAxODIw&refRm=11",
    logoSrc: "/brokers/coinexx.svg",
  },
  plexytrade: {
    id: "plexytrade",
    name: "PlexyTrade",
    type: "offshore",
    region: "BOTH",
    rating: 3.0,
    minDeposit: 50,
    minDepositDisplay: "$50",
    leverage: "1:2000",
    leverageValue: 2000,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "Unregulated (St. Lucia)",
    headquarters: "St. Lucia",
    foundedYear: 2024,
    usAccepted: true,
    platforms: ["MT4", "MT5"],
    accountTypes: ["Standard", "ECN", "VIP"],
    paymentMethods: ["Bitcoin", "Ethereum", "USDT", "Crypto"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.5,
      platformTools: 7.5,
      customerSupport: 7.0,
      depositWithdrawal: 8.0,
      trustReputation: 6.0,
    },
    pros: [
      "Accepts US clients",
      "Highest leverage available (1:2000)",
      "Zero spread accounts",
      "Good Trustpilot rating (4.4/5)",
      "Built on LQDFX infrastructure",
    ],
    cons: [
      "Very new broker (2024)",
      "Unregulated",
      "Crypto-only deposits",
      "Limited track record",
    ],
    reviewUrl: "/review/plexytrade",
    siteUrl: "https://www.plexytrade.com",
    affiliateUrl: "", // Will be added after IB setup
    logoSrc: "/brokers/plexytrade.svg",
  },
  exness: {
    id: "exness",
    name: "Exness",
    type: "regulated",
    region: "INTL",
    rating: 3.8,
    minDeposit: 10,
    minDepositDisplay: "$10",
    leverage: "1:2000",
    leverageValue: 2000,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "FCA, CySEC, FSA, FSCA",
    headquarters: "Cyprus",
    foundedYear: 2008,
    usAccepted: false,
    platforms: ["MT4", "MT5", "Exness Terminal"],
    accountTypes: ["Standard", "Standard Cent", "Pro", "Raw Spread", "Zero"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller", "Crypto", "Papara"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.5,
      platformTools: 9.0,
      customerSupport: 9.0,
      depositWithdrawal: 9.5,
      trustReputation: 9.5,
    },
    pros: [
      "Multi-regulated (FCA, CySEC)",
      "Excellent Trustpilot rating (4.8/5)",
      "Ultra-low spreads from 0.0 pips",
      "High leverage up to 1:2000",
      "Instant withdrawals",
      "No minimum deposit on Standard",
      "Turkish language support",
    ],
    cons: [
      "US clients NOT accepted",
      "High leverage = high risk",
      "Limited educational content",
    ],
    reviewUrl: "/review/exness",
    siteUrl: "https://www.exness.com",
    affiliateUrl: "",
    logoSrc: "/brokers/exness.svg",
  },
  pepperstone: {
    id: "pepperstone",
    name: "Pepperstone",
    type: "regulated",
    region: "INTL",
    rating: 3.6,
    minDeposit: 0,
    minDepositDisplay: "$0",
    leverage: "1:500",
    leverageValue: 500,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "FCA, ASIC, CySEC, BaFIN, SCB",
    headquarters: "Australia",
    foundedYear: 2010,
    usAccepted: false,
    platforms: ["MT4", "MT5", "cTrader", "TradingView"],
    accountTypes: ["Standard", "Razor"],
    paymentMethods: ["Credit Card", "Wire Transfer", "PayPal", "Skrill", "Neteller"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 9.0,
      platformTools: 9.5,
      customerSupport: 8.5,
      depositWithdrawal: 9.0,
      trustReputation: 9.0,
    },
    pros: [
      "Multi-regulated (FCA, ASIC, CySEC)",
      "Excellent trading platforms including cTrader",
      "Raw spreads from 0.0 pips",
      "No minimum deposit",
      "Fast execution speeds",
      "Good for scalpers",
    ],
    cons: [
      "US clients NOT accepted",
      "No proprietary platform",
      "Limited educational resources",
    ],
    reviewUrl: "/review/pepperstone",
    siteUrl: "https://www.pepperstone.com",
    affiliateUrl: "",
    logoSrc: "/brokers/pepperstone.svg",
  },
  xm: {
    id: "xm",
    name: "XM",
    type: "regulated",
    region: "BOTH",
    rating: 4.5,
    featured: true,
    minDeposit: 5,
    minDepositDisplay: "$5",
    leverage: "1:1000",
    leverageValue: 1000,
    spreads: "1.0 pips",
    spreadsFrom: 1.0,
    regulation: "CySEC, ASIC, DFSA, FSC",
    headquarters: "Cyprus",
    foundedYear: 2009,
    usAccepted: false,
    platforms: ["MT4", "MT5", "XM App"],
    accountTypes: ["Micro", "Standard", "XM Ultra Low", "Shares"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.0,
      platformTools: 8.5,
      customerSupport: 8.5,
      depositWithdrawal: 8.5,
      trustReputation: 8.5,
    },
    pros: [
      "Multi-regulated broker",
      "Low minimum deposit ($5)",
      "High leverage (1:1000)",
      "Excellent educational content",
      "Regular webinars and seminars",
      "No deposit/withdrawal fees",
    ],
    cons: [
      "US clients NOT accepted",
      "Higher spreads than ECN brokers",
      "Inactivity fees apply",
    ],
    reviewUrl: "/review/xm",
    siteUrl: "https://affs.click/j5QmR",
    affiliateUrl: "https://affs.click/n3dTY",
    logoSrc: "/brokers/xm.svg",
  },
  fxtm: {
    id: "fxtm",
    name: "FXTM (ForexTime)",
    type: "regulated",
    region: "INTL",
    rating: 3.1,
    minDeposit: 10,
    minDepositDisplay: "$10",
    leverage: "1:2000",
    leverageValue: 2000,
    spreads: "0.0 pips",
    spreadsFrom: 0,
    regulation: "FCA, CySEC, FSCA, FSC",
    headquarters: "Cyprus",
    foundedYear: 2011,
    usAccepted: false,
    platforms: ["MT4", "MT5", "FXTM Trader"],
    accountTypes: ["Micro", "Advantage", "Advantage Plus"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.0,
      platformTools: 8.0,
      customerSupport: 7.5,
      depositWithdrawal: 7.5,
      trustReputation: 8.0,
    },
    pros: [
      "Multi-regulated (FCA, CySEC)",
      "High leverage up to 1:2000",
      "Low minimum deposit",
      "Copy trading available",
      "Good educational resources",
    ],
    cons: [
      "US clients NOT accepted",
      "Mixed recent reviews",
      "Some withdrawal delays reported",
    ],
    reviewUrl: "/review/fxtm",
    siteUrl: "https://www.forextime.com",
    affiliateUrl: "",
    logoSrc: "/brokers/fxtm.svg",
  },
  fbs: {
    id: "fbs",
    name: "FBS",
    type: "regulated",
    region: "INTL",
    rating: 3.0,
    minDeposit: 5,
    minDepositDisplay: "$5",
    leverage: "1:3000",
    leverageValue: 3000,
    spreads: "0.5 pips",
    spreadsFrom: 0.5,
    regulation: "CySEC, ASIC, FSC",
    headquarters: "Belize",
    foundedYear: 2009,
    usAccepted: false,
    platforms: ["MT4", "MT5", "FBS Trader"],
    accountTypes: ["Cent", "Micro", "Standard", "Zero Spread", "ECN"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller", "Crypto"],
    cryptoDeposits: true,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 8.5,
      platformTools: 8.0,
      customerSupport: 8.0,
      depositWithdrawal: 8.5,
      trustReputation: 8.0,
    },
    pros: [
      "Highest leverage (1:3000)",
      "Very low minimum deposit ($5)",
      "Multiple account types",
      "Good bonus programs",
      "Crypto deposits accepted",
      "15+ years experience",
    ],
    cons: [
      "US clients NOT accepted",
      "Offshore entity for high leverage",
      "Mixed reviews on withdrawals",
    ],
    reviewUrl: "/review/fbs",
    siteUrl: "https://www.fbs.com",
    affiliateUrl: "",
    logoSrc: "/brokers/fbs.svg",
  },
  avatrade: {
    id: "avatrade",
    name: "AvaTrade",
    type: "regulated",
    region: "INTL",
    rating: 3.3,
    minDeposit: 100,
    minDepositDisplay: "$100",
    leverage: "1:400",
    leverageValue: 400,
    spreads: "0.9 pips",
    spreadsFrom: 0.9,
    regulation: "CBI, ASIC, FSCA",
    headquarters: "Ireland",
    foundedYear: 2006,
    usAccepted: false,
    platforms: ["AvaTradeGO", "MT4", "MT5"],
    accountTypes: ["Retail", "Professional"],
    paymentMethods: ["Credit Card", "Wire Transfer", "Skrill", "Neteller"],
    cryptoDeposits: false,
    negativeBalanceProtection: true,
    scores: {
      tradingConditions: 7.5,
      platformTools: 8.5,
      customerSupport: 8.0,
      depositWithdrawal: 8.0,
      trustReputation: 8.5,
    },
    pros: [
      "Multi-regulated broker",
      "Higher leverage available",
      "AvaProtect feature",
      "Good mobile app",
    ],
    cons: [
      "US clients NOT accepted",
      "Average spreads",
      "Inactivity fees",
    ],
    reviewUrl: "/review/avatrade",
    siteUrl: "https://www.avatrade.com",
    logoSrc: "/brokers/avatrade.svg",
  },
};

// Helper function to get average score
export const getAverageScore = (broker: Broker): number => {
  const scores = broker.scores;
  const total = scores.tradingConditions + scores.platformTools + scores.customerSupport + scores.depositWithdrawal + scores.trustReputation;
  return Math.round((total / 5) * 10) / 10;
};

// Sorted broker lists
export const topBrokers = Object.values(brokers).sort((a, b) => b.rating - a.rating);

export const reviewedBrokers = topBrokers;

export const usAcceptedBrokers = topBrokers.filter(b => b.usAccepted);

export const offshoreBrokers = topBrokers.filter(b => b.type === "offshore");

export const regulatedBrokers = topBrokers.filter(b => b.type === "regulated");

// Region-based broker lists
export const usBrokers = topBrokers.filter(b => b.region === "US" || b.region === "BOTH");

export const intlBrokers = topBrokers.filter(b => b.region === "INTL" || b.region === "BOTH");
